# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '__first__'),
        ('authrole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', to='auth.Permission', verbose_name='Permissions'),
        ),
    ]
